package com.common.entity.goods;

import java.util.Date;

/**
 * 类目
 * @Version V1.0.0
 * @Author  bowen
 * @CreateDate  2016/10/28下午9:10
 *
*/
public class Category {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category.category_id
     *
     * @mbggenerated
     */
    private Integer categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category.category_name
     *
     * @mbggenerated
     */
    private String categoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category.category_parent_id
     *
     * @mbggenerated
     */
    private Integer categoryParentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category.category_order_num
     *
     * @mbggenerated
     */
    private Integer categoryOrderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_category.last_update_date
     *
     * @mbggenerated
     */
    private Date lastUpdateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category.category_id
     *
     * @return the value of t_category.category_id
     *
     * @mbggenerated
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category.category_id
     *
     * @param categoryId the value for t_category.category_id
     *
     * @mbggenerated
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category.category_name
     *
     * @return the value of t_category.category_name
     *
     * @mbggenerated
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category.category_name
     *
     * @param categoryName the value for t_category.category_name
     *
     * @mbggenerated
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category.category_parent_id
     *
     * @return the value of t_category.category_parent_id
     *
     * @mbggenerated
     */
    public Integer getCategoryParentId() {
        return categoryParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category.category_parent_id
     *
     * @param categoryParentId the value for t_category.category_parent_id
     *
     * @mbggenerated
     */
    public void setCategoryParentId(Integer categoryParentId) {
        this.categoryParentId = categoryParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category.category_order_num
     *
     * @return the value of t_category.category_order_num
     *
     * @mbggenerated
     */
    public Integer getCategoryOrderNum() {
        return categoryOrderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category.category_order_num
     *
     * @param categoryOrderNum the value for t_category.category_order_num
     *
     * @mbggenerated
     */
    public void setCategoryOrderNum(Integer categoryOrderNum) {
        this.categoryOrderNum = categoryOrderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category.create_date
     *
     * @return the value of t_category.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category.create_date
     *
     * @param createDate the value for t_category.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_category.last_update_date
     *
     * @return the value of t_category.last_update_date
     *
     * @mbggenerated
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_category.last_update_date
     *
     * @param lastUpdateDate the value for t_category.last_update_date
     *
     * @mbggenerated
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }
}