package com.common.entity.goods;

import com.common.entity.picfile.PicFile;

import java.util.Date;

/**
 * 商品主表实体类
 * @Version V1.0.0
 * @Author  bowen
 * @CreateDate  2016/10/28下午9:08
 *
*/
public class Goods {
    /**
     * 商品ID
     */
    private Integer goodsId;

    /**
     * 主标题
     */
    private String goodsTitle;

    /**
     * 副标题
     */
    private String goodsSubTitle;

    /**
     * 主图
     */
    private PicFile goodsPicFile;

    /**
     * 图文详情
     */
    private String goodsDetailHtml;

    /**
     * 商品详情
     */
    private String goodsDetailHtmlUrl;

    /**
     * 创建时间
     */
    private Date createDate;

    /**
     * 最后更新时间
     */
    private Date lastUpdateDate;

    /**
     * 是否上线
     */
    private Boolean goodsOnline;

    /**
     * 季节ID
     */
    private Integer goodsSeasonId;

    /**
     * 一级类目
     */
    private Integer goodsCategoryFirst;

    /**
     * 二级类目
     */
    private Integer goodsCategorySecond;

    /**
     * 三级类目
     */
    private Integer goodsCategoryThird;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.goods_id
     *
     * @return the value of t_goods.goods_id
     *
     * @mbggenerated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.goods_id
     *
     * @param goodsId the value for t_goods.goods_id
     *
     * @mbggenerated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.goods_title
     *
     * @return the value of t_goods.goods_title
     *
     * @mbggenerated
     */
    public String getGoodsTitle() {
        return goodsTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.goods_title
     *
     * @param goodsTitle the value for t_goods.goods_title
     *
     * @mbggenerated
     */
    public void setGoodsTitle(String goodsTitle) {
        this.goodsTitle = goodsTitle == null ? null : goodsTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.goods_sub_title
     *
     * @return the value of t_goods.goods_sub_title
     *
     * @mbggenerated
     */
    public String getGoodsSubTitle() {
        return goodsSubTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.goods_sub_title
     *
     * @param goodsSubTitle the value for t_goods.goods_sub_title
     *
     * @mbggenerated
     */
    public void setGoodsSubTitle(String goodsSubTitle) {
        this.goodsSubTitle = goodsSubTitle == null ? null : goodsSubTitle.trim();
    }

    public PicFile getGoodsPicFile() {
        return goodsPicFile;
    }

    public void setGoodsPicFile(PicFile goodsPicFile) {
        this.goodsPicFile = goodsPicFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.goods_detail_html
     *
     * @return the value of t_goods.goods_detail_html
     *
     * @mbggenerated
     */
    public String getGoodsDetailHtml() {
        return goodsDetailHtml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.goods_detail_html
     *
     * @param goodsDetailHtml the value for t_goods.goods_detail_html
     *
     * @mbggenerated
     */
    public void setGoodsDetailHtml(String goodsDetailHtml) {
        this.goodsDetailHtml = goodsDetailHtml == null ? null : goodsDetailHtml.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.goods_detail_html_url
     *
     * @return the value of t_goods.goods_detail_html_url
     *
     * @mbggenerated
     */
    public String getGoodsDetailHtmlUrl() {
        return goodsDetailHtmlUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.goods_detail_html_url
     *
     * @param goodsDetailHtmlUrl the value for t_goods.goods_detail_html_url
     *
     * @mbggenerated
     */
    public void setGoodsDetailHtmlUrl(String goodsDetailHtmlUrl) {
        this.goodsDetailHtmlUrl = goodsDetailHtmlUrl == null ? null : goodsDetailHtmlUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.create_date
     *
     * @return the value of t_goods.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.create_date
     *
     * @param createDate the value for t_goods.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.last_update_date
     *
     * @return the value of t_goods.last_update_date
     *
     * @mbggenerated
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.last_update_date
     *
     * @param lastUpdateDate the value for t_goods.last_update_date
     *
     * @mbggenerated
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.goods_online
     *
     * @return the value of t_goods.goods_online
     *
     * @mbggenerated
     */
    public Boolean getGoodsOnline() {
        return goodsOnline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.goods_online
     *
     * @param goodsOnline the value for t_goods.goods_online
     *
     * @mbggenerated
     */
    public void setGoodsOnline(Boolean goodsOnline) {
        this.goodsOnline = goodsOnline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.goods_season_id
     *
     * @return the value of t_goods.goods_season_id
     *
     * @mbggenerated
     */
    public Integer getGoodsSeasonId() {
        return goodsSeasonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.goods_season_id
     *
     * @param goodsSeasonId the value for t_goods.goods_season_id
     *
     * @mbggenerated
     */
    public void setGoodsSeasonId(Integer goodsSeasonId) {
        this.goodsSeasonId = goodsSeasonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.goods_category_first
     *
     * @return the value of t_goods.goods_category_first
     *
     * @mbggenerated
     */
    public Integer getGoodsCategoryFirst() {
        return goodsCategoryFirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.goods_category_first
     *
     * @param goodsCategoryFirst the value for t_goods.goods_category_first
     *
     * @mbggenerated
     */
    public void setGoodsCategoryFirst(Integer goodsCategoryFirst) {
        this.goodsCategoryFirst = goodsCategoryFirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.goods_category_second
     *
     * @return the value of t_goods.goods_category_second
     *
     * @mbggenerated
     */
    public Integer getGoodsCategorySecond() {
        return goodsCategorySecond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.goods_category_second
     *
     * @param goodsCategorySecond the value for t_goods.goods_category_second
     *
     * @mbggenerated
     */
    public void setGoodsCategorySecond(Integer goodsCategorySecond) {
        this.goodsCategorySecond = goodsCategorySecond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.goods_category_third
     *
     * @return the value of t_goods.goods_category_third
     *
     * @mbggenerated
     */
    public Integer getGoodsCategoryThird() {
        return goodsCategoryThird;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.goods_category_third
     *
     * @param goodsCategoryThird the value for t_goods.goods_category_third
     *
     * @mbggenerated
     */
    public void setGoodsCategoryThird(Integer goodsCategoryThird) {
        this.goodsCategoryThird = goodsCategoryThird;
    }

}