package com.common.entity.goods;

/**
 * 颜色
 * @Author  bowen
 * @CreateDate  2016/11/3上午11:13
 * 
*/
public class GoodsColor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_color.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_color.color_name
     *
     * @mbggenerated
     */
    private String colorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_color.order_num
     *
     * @mbggenerated
     */
    private Integer orderNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_color.id
     *
     * @return the value of t_goods_color.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_color.id
     *
     * @param id the value for t_goods_color.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_color.color_name
     *
     * @return the value of t_goods_color.color_name
     *
     * @mbggenerated
     */
    public String getColorName() {
        return colorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_color.color_name
     *
     * @param colorName the value for t_goods_color.color_name
     *
     * @mbggenerated
     */
    public void setColorName(String colorName) {
        this.colorName = colorName == null ? null : colorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_color.order_num
     *
     * @return the value of t_goods_color.order_num
     *
     * @mbggenerated
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_color.order_num
     *
     * @param orderNum the value for t_goods_color.order_num
     *
     * @mbggenerated
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }
}