package com.common.entity.goods;

/**
 * 商品列表价格实体类,仅仅作列表商品价格显示用,
 * 该数据是通过goods_price定时计算维护而成,商品SKU实时价格以goods_price为准
 * @Author  bowen
 * @CreateDate  2016/11/6上午10:05
 *
*/
public class GoodsListPrice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_list_price.goods_id
     *
     * @mbggenerated
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_list_price.price
     *
     * @mbggenerated
     */
    private Integer price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_list_price.goods_id
     *
     * @return the value of t_goods_list_price.goods_id
     *
     * @mbggenerated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_list_price.goods_id
     *
     * @param goodsId the value for t_goods_list_price.goods_id
     *
     * @mbggenerated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_list_price.price
     *
     * @return the value of t_goods_list_price.price
     *
     * @mbggenerated
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_list_price.price
     *
     * @param price the value for t_goods_list_price.price
     *
     * @mbggenerated
     */
    public void setPrice(Integer price) {
        this.price = price;
    }
}