package com.common.entity.goods;

/**
 * 尺码
 * @Author  bowen
 * @CreateDate  2016/11/3上午11:12
 * 
*/
public class GoodsSize {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_size.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_size.size_name
     *
     * @mbggenerated
     */
    private String sizeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods_size.order_num
     *
     * @mbggenerated
     */
    private Integer orderNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_size.id
     *
     * @return the value of t_goods_size.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_size.id
     *
     * @param id the value for t_goods_size.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_size.size_name
     *
     * @return the value of t_goods_size.size_name
     *
     * @mbggenerated
     */
    public String getSizeName() {
        return sizeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_size.size_name
     *
     * @param sizeName the value for t_goods_size.size_name
     *
     * @mbggenerated
     */
    public void setSizeName(String sizeName) {
        this.sizeName = sizeName == null ? null : sizeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods_size.order_num
     *
     * @return the value of t_goods_size.order_num
     *
     * @mbggenerated
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods_size.order_num
     *
     * @param orderNum the value for t_goods_size.order_num
     *
     * @mbggenerated
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }
}