package com.common.entity.picfile;

import java.util.Date;

/**
 * 图片文件实体类
 * @Author  bowen
 * @CreateDate  2016/11/1下午3:23
 * 
*/
public class PicFile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pic_file.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pic_file.file_name
     *
     * @mbggenerated
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pic_file.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pic_file.bucket_name
     *
     * @mbggenerated
     */
    private String bucketName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pic_file.id
     *
     * @return the value of t_pic_file.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pic_file.id
     *
     * @param id the value for t_pic_file.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pic_file.file_name
     *
     * @return the value of t_pic_file.file_name
     *
     * @mbggenerated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pic_file.file_name
     *
     * @param fileName the value for t_pic_file.file_name
     *
     * @mbggenerated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pic_file.create_date
     *
     * @return the value of t_pic_file.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pic_file.create_date
     *
     * @param createDate the value for t_pic_file.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pic_file.bucket_name
     *
     * @return the value of t_pic_file.bucket_name
     *
     * @mbggenerated
     */
    public String getBucketName() {
        return bucketName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pic_file.bucket_name
     *
     * @param bucketName the value for t_pic_file.bucket_name
     *
     * @mbggenerated
     */
    public void setBucketName(String bucketName) {
        this.bucketName = bucketName == null ? null : bucketName.trim();
    }

    public PicFile() {
    }

    public PicFile(Integer id) {
        this.id = id;
    }

    public PicFile(String fileName, String bucketName) {
        this.fileName = fileName;
        this.bucketName = bucketName;
    }

    public PicFile(Integer id, String fileName, Date createDate, String bucketName) {
        this.id = id;
        this.fileName = fileName;
        this.createDate = createDate;
        this.bucketName = bucketName;
    }
}